// Soprano inside the Lab worker, on ONNX Runtime (there is no Transformers.js
// class for it; only the tokenizer comes from Transformers.js).
//
// Two small networks, as in the reference code (github.com/ekwek1/soprano):
//  - the backbone, a 17-layer Qwen3-style language model, reads
//    "[STOP][TEXT]<text>[START]" and writes audio tokens one at a time
//    (greedy, repetition penalty 1.2: the reference defaults). The hidden
//    state that predicts each token is what gets turned into sound.
//    One addition: this int8 export now and then keeps talking past the end
//    of a sentence (repeating its last word) where the full-precision model
//    stops. So once a sentence runs longer than its text suggests, [STOP]
//    gets a gentle, growing nudge. On 18 test sentences it changed only the one
//    that ran on (103 tokens down to 85; the reference model made 78).
//  - the decoder (a Vocos-style vocoder) turns those hidden states into
//    32 kHz audio, 2048 samples per token.
// Audio comes out while the sentence is still being written: each call makes
// a few more tokens and decodes the stretch that no future token can change
// (the decoder looks 4 tokens either side).
//   { op: 'begin', text }      a cleaned sentence             -> { tokens }
//   { op: 'more', count }      up to `count` more tokens      -> { audio, done, made }

const BACKBONE = 'onnx/soprano_backbone_kv_int8.onnx';
const LAYERS = 17, HEADS_KV = 1, HEAD_DIM = 128, HIDDEN = 512, VOCAB = 8192;
const STOP = 3;            // [STOP] ends the audio
const PENALTY = 1.2;
const MAX_TOKENS = 512;    // per sentence, as upstream (about 33 s)
// Audio tokens a cleaned sentence usually takes: fitted on 18 sentences
// generated by the reference PyTorch model (within 15% either way).
const expected = (text) => 8 + 0.74 * text.length;
const NUDGE = 4;           // added to [STOP]'s score per 100% over that length
const HOP = 2048;          // samples per token
const RF = 4;              // decoder reach, in tokens, either side
const FADE = 512;          // samples blended where two decoded stretches meet

export async function load(T, { model, dtype, progress_callback, fetchFile, ort }) {
  const fp32Decoder = (dtype?.decoder || 'q8') === 'fp32';
  const opts = { executionProviders: ['wasm'], graphOptimizationLevel: 'all' };
  const [tok, rt, backboneBytes] = await Promise.all([
    T.AutoTokenizer.from_pretrained(model, { progress_callback }),
    ort(),
    fetchFile(BACKBONE),
  ]);
  const backbone = await rt.InferenceSession.create(backboneBytes, opts);
  let decoder;
  if (fp32Decoder) {
    const [graph, data] = await Promise.all([fetchFile('onnx/soprano_decoder_fp32.onnx'), fetchFile('onnx/soprano_decoder_fp32.onnx.data')]);
    decoder = await rt.InferenceSession.create(graph, { ...opts, externalData: [{ path: 'soprano_decoder_fp32.onnx.data', data }] });
  } else {
    decoder = await rt.InferenceSession.create(await fetchFile('onnx/soprano_decoder_int8.onnx'), opts);
  }
  return { tok, rt, backbone, decoder, job: null };
}

// The first passes are several times slower than the rest; pay for them now.
export async function warm(pipe) {
  begin(pipe, 'hello there.');
  await more(pipe, 14);
  pipe.job = null;
}

export async function run(pipe, input) {
  if (input.op === 'begin') return { output: begin(pipe, input.text) };
  const out = await more(pipe, input.count);
  return { output: out, transfer: [out.audio.buffer] };
}

function begin(pipe, text) {
  const ids = Array.from(pipe.tok.encode(`[STOP][TEXT]${text}[START]`, { add_special_tokens: false }));
  const seen = new Uint8Array(VOCAB);
  ids.forEach((i) => { seen[i] = 1; });
  pipe.job = { input: ids, pos: 0, past: null, seen, seenList: [...new Set(ids)], hidden: [], done: false, emitted: 0, tail: null,
    expect: expected(text), cap: Math.min(MAX_TOKENS, Math.ceil(2 * expected(text) + 24)) };
  return { tokens: ids.length };
}

async function step(pipe) {
  const { rt, backbone } = pipe, job = pipe.job;
  const n = job.input.length, total = job.pos + n;
  const feeds = {
    input_ids: new rt.Tensor('int64', BigInt64Array.from(job.input, BigInt), [1, n]),
    attention_mask: new rt.Tensor('int64', new BigInt64Array(total).fill(1n), [1, total]),
    position_ids: new rt.Tensor('int64', BigInt64Array.from({ length: n }, (_, i) => BigInt(job.pos + i)), [1, n]),
  };
  for (let l = 0; l < LAYERS; l++) {
    for (const kv of ['key', 'value']) {
      feeds[`past_key_values.${l}.${kv}`] = job.past?.[`present.${l}.${kv}`]
        ?? new rt.Tensor('float32', new Float32Array(0), [1, HEADS_KV, 0, HEAD_DIM]);
    }
  }
  const r = await backbone.run(feeds);
  job.past = r;
  job.pos = total;

  // Greedy pick after the repetition penalty (every token seen so far, prompt included).
  const logits = r.logits.data.subarray((n - 1) * VOCAB, n * VOCAB);
  const scores = Float32Array.from(logits);
  for (const id of job.seenList) { const s = scores[id]; scores[id] = s < 0 ? s * PENALTY : s / PENALTY; }
  const over = job.hidden.length / job.expect - 1;
  if (over > 0) scores[STOP] += NUDGE * over;
  let best = 0;
  for (let v = 1; v < VOCAB; v++) if (scores[v] > scores[best]) best = v;

  if (best === STOP) { job.done = true; return; }
  job.hidden.push(r.last_hidden_state.data.slice((n - 1) * HIDDEN, n * HIDDEN));
  if (!job.seen[best]) { job.seen[best] = 1; job.seenList.push(best); }
  job.input = [best];
  if (job.hidden.length >= job.cap) job.done = true;
}

// Also says how long a token takes once the prompt is read, so the page can
// tell whether playback can start now without running out.
async function more(pipe, count) {
  const job = pipe.job;
  if (!job) throw new Error('Nothing to say');
  let steps = 0, stepMs = 0;
  for (let i = 0; i < count && !job.done; i++) {
    const first = job.pos === 0, t0 = performance.now();
    await step(pipe);
    if (!first) { steps++; stepMs += performance.now() - t0; }
  }
  const t1 = performance.now();
  const { audio, win } = await emit(pipe);
  if (job.done) job.past = null;
  return { audio, done: job.done, made: job.hidden.length, msPerToken: steps ? stepMs / steps : null, decodeMsPerToken: win ? (performance.now() - t1) / win : null };
}

// Decode the stretch from the last emitted token up to the last one that is
// final, with RF tokens of context on each side. Positions are token indices;
// the decoder turns tokens a..b into samples for positions a..b, 2048 each.
async function emit(pipe) {
  const { rt, decoder } = pipe, job = pipe.job;
  const H = job.hidden, N = H.length;
  const upto = job.done ? N - 1 : N - 1 - RF;
  if (N < 2 || upto <= job.emitted) return { audio: new Float32Array(0), win: 0 };
  const a = Math.max(0, job.emitted - RF), b = N - 1, w = b - a + 1;
  const x = new Float32Array(HIDDEN * w);
  for (let t = 0; t < w; t++) { const h = H[a + t]; for (let c = 0; c < HIDDEN; c++) x[c * w + t] = h[c]; }
  const { audio } = await decoder.run({ hidden_states: new rt.Tensor('float32', x, [1, HIDDEN, w]) });
  const y = audio.data;
  const from = HOP * (job.emitted - a), to = HOP * (upto - a);
  const out = y.slice(from, to);
  // With the int8 decoder two windows don't meet exactly (its rounding depends
  // a little on the whole window), so a short crossfade hides the seam. With
  // the fp32 decoder they match and the fade changes nothing.
  if (job.tail) {
    const k = Math.min(FADE, job.tail.length, out.length);
    for (let i = 0; i < k; i++) { const g = (i + 0.5) / k; out[i] = job.tail[i] * (1 - g) + out[i] * g; }
  }
  job.tail = job.done ? null : y.slice(to, Math.min(y.length, to + FADE));
  job.emitted = upto;
  return { audio: out, win: w };
}
