// Hand-picked, checked live on Sep 25, 2026. No parked domains, no ad farms.
// vibe: calm | play | weird | learn | make
export const SITES = [
  // calm
  ['https://www.window-swap.com/', 'WindowSwap', 'someone else’s window, somewhere in the world', 'calm'],
  ['https://radio.garden/', 'Radio Garden', 'spin the globe, listen to local radio', 'calm'],
  ['https://asoftmurmur.com/', 'A Soft Murmur', 'rain, thunder and waves to mix', 'calm'],
  ['https://mynoise.net/', 'myNoise', 'the deep end of background noise', 'calm'],
  ['https://pixelthoughts.co/', 'Pixel Thoughts', 'a sixty second reset for a busy head', 'calm'],
  ['https://zoomquilt.org/', 'Zoomquilt', 'a painting that zooms forever', 'calm'],
  ['https://earth.nullschool.net/', 'earth', 'live wind and ocean currents, the whole planet', 'calm'],
  ['https://www.windy.com/', 'Windy', 'weather as moving art', 'calm'],
  ['https://www.lightningmaps.org/', 'LightningMaps', 'lightning striking right now', 'calm'],
  ['https://studytogether.com/', 'Study Together', 'a room full of people quietly working', 'calm'],
  ['https://thisissand.com/', 'This Is Sand', 'pour sand, make layers', 'calm'],
  ['http://weavesilk.com/', 'Silk', 'draw with symmetrical light', 'calm'],
  ['https://oskarstalberg.com/Townscaper/', 'Townscaper', 'click water, a town grows', 'calm'],
  ['https://orb.farm/', 'Orb.Farm', 'a tiny aquatic ecosystem to keep alive', 'calm'],

  // play
  ['https://findtheinvisiblecow.com/', 'Find the Invisible Cow', 'the original', 'play'],
  ['https://neal.fun/password-game/', 'The Password Game', 'the rules get worse', 'play'],
  ['https://neal.fun/infinite-craft/', 'Infinite Craft', 'combine things until you make everything', 'play'],
  ['https://neal.fun/perfect-circle/', 'Draw a Perfect Circle', 'harder than it sounds', 'play'],
  ['https://neal.fun/not-a-robot/', 'I’m Not a Robot', 'captchas, escalating', 'play'],
  ['https://neal.fun/logos-from-memory/', 'Logos from Memory', 'draw brands you see every day', 'play'],
  ['https://neal.fun/spend/', 'Spend Bill Gates’ Money', 'try to run out', 'play'],
  ['https://checkboxrace.com/', 'Checkbox Race', 'tick boxes, fast', 'play'],
  ['https://onesquareminesweeper.com/', 'One Square Minesweeper', 'good luck', 'play'],
  ['https://touchpianist.com/', 'Touch Pianist', 'tap in rhythm, play Chopin', 'play'],
  ['https://www.incredibox.com/', 'Incredibox', 'drag outfits onto beatboxers', 'play'],
  ['https://quickdraw.withgoogle.com/', 'Quick, Draw!', 'a neural net guesses your doodles', 'play'],
  ['https://sandspiel.club/', 'Sandspiel', 'falling sand, fire, plants, lava', 'play'],
  ['https://neal.fun/sandboxels/', 'Sandboxels', 'hundreds of elements to mix and melt', 'play'],
  ['https://www.koalastothemax.com/', 'Koalas to the Max', 'hover until a picture appears', 'play'],
  ['https://www.mapcrunch.com/', 'MapCrunch', 'dropped somewhere on Street View', 'play'],
  ['https://neal.fun/asteroid-launcher/', 'Asteroid Launcher', 'pick a rock, pick a city', 'play'],
  ['https://neal.fun/absurd-trolley-problems/', 'Absurd Trolley Problems', 'moral choices, badly', 'play'],
  ['https://smashthewalls.com/', 'Smash the Walls', 'break the page', 'play'],

  // weird
  ['https://pointerpointer.com/', 'Pointer Pointer', 'photos of people pointing at your cursor', 'weird'],
  ['https://cat-bounce.com/', 'Cat Bounce', 'cats. bouncing.', 'weird'],
  ['https://heeeeeeeey.com/', 'HEEEEEEEEY', 'hey', 'weird'],
  ['https://hooooooooo.com/', 'HOOOOOOOOO', 'ho', 'weird'],
  ['https://longdogechallenge.com/', 'Long Doge Challenge', 'how long is the doge', 'weird'],
  ['https://www.omfgdogs.com/', 'OMFGDOGS', 'dogs, running, forever', 'weird'],
  ['https://eelslap.com/', 'Eel Slap', 'move your mouse. sorry.', 'weird'],
  ['https://www.puginarug.com/', 'Pug in a Rug', 'a pug, in a rug', 'weird'],
  ['https://crouton.net/', 'Crouton', 'a crouton', 'weird'],
  ['https://www.rrrgggbbb.com/', 'RRR GGG BBB', 'colour, at you', 'weird'],
  ['https://www.cachemonet.com/', 'Cache Monet', 'impressionism, but gifs', 'weird'],
  ['https://bouncingdvdlogo.com/', 'Bouncing DVD Logo', 'will it hit the corner', 'weird'],
  ['https://hackertyper.net/', 'Hacker Typer', 'type anything, look busy', 'weird'],
  ['https://clickclickclick.click/', 'Click Click Click', 'it is watching you click', 'weird'],
  ['https://cant-not-tweet-this.com/', 'Can’t Not Tweet This', 'the name says it', 'weird'],
  ['https://www.trypap.com/', 'Passive Aggressive Passwords', 'a login form with opinions', 'weird'],
  ['https://pixelsfighting.com/', 'Pixels Fighting', 'two colours, one screen', 'weird'],
  ['https://www.fallingfalling.com/', 'Falling Falling', 'net art by Rafaël Rozendaal', 'weird'],
  ['https://www.muchbetterthanthis.com/', 'Much Better Than This', 'net art by Rafaël Rozendaal', 'weird'],
  ['https://www.yesnoif.com/', 'Yes No If', 'net art by Rafaël Rozendaal', 'weird'],
  ['https://www.spacejam.com/1996/', 'Space Jam (1996)', 'the website, untouched since 1996', 'weird'],
  ['https://www.cameronsworld.net/', 'Cameron’s World', 'a collage of old GeoCities pages', 'weird'],
  ['https://www.windows93.net/', 'Windows 93', 'an operating system that never was', 'weird'],
  ['https://floor796.com/', 'Floor796', 'one giant animated space station', 'weird'],

  // learn
  ['https://neal.fun/deep-sea/', 'The Deep Sea', 'scroll down to the bottom of the ocean', 'learn'],
  ['https://neal.fun/space-elevator/', 'Space Elevator', 'scroll up to space', 'learn'],
  ['https://neal.fun/size-of-space/', 'The Size of Space', 'from astronaut to universe', 'learn'],
  ['https://neal.fun/size-of-life/', 'The Size of Life', 'from DNA to blue whale', 'learn'],
  ['https://neal.fun/life-stats/', 'Life Stats', 'your life so far, in numbers', 'learn'],
  ['https://neal.fun/internet-artifacts/', 'Internet Artifacts', 'a museum of the web', 'learn'],
  ['https://neal.fun/wonders-of-street-view/', 'Wonders of Street View', 'the strangest things cameras caught', 'learn'],
  ['https://ncase.me/trust/', 'The Evolution of Trust', 'game theory you can play', 'learn'],
  ['https://ncase.me/polygons/', 'Parable of the Polygons', 'how small bias builds segregation', 'learn'],
  ['https://ncase.me/loopy/', 'LOOPY', 'draw systems, watch them run', 'learn'],
  ['https://playgameoflife.com/', 'Game of Life', 'Conway’s cellular automaton', 'learn'],
  ['https://pudding.cool/', 'The Pudding', 'visual essays about culture', 'learn'],
  ['https://lines.chromeexperiments.com/', 'Land Lines', 'draw a line, find it in satellite photos', 'learn'],
  ['https://obscurifymusic.com/', 'Obscurify', 'how unusual your music taste is', 'learn'],

  // make
  ['https://paint.toys/', 'Paint Toys', 'brushes that behave strangely', 'make'],
  ['https://sliding.toys/', 'Sliding Toys', 'make a sliding puzzle', 'make'],
  ['https://drawing.garden/', 'Drawing Garden', 'draw a garden that grows', 'make'],
  ['https://jspaint.app/', 'JS Paint', 'MS Paint, in a tab', 'make'],
  ['https://typatone.com/', 'Typatone', 'type words, make music', 'make'],
  ['https://musiclab.chromeexperiments.com/Experiments', 'Chrome Music Lab', 'toys for making music', 'make'],
  ['https://bongo.cat/', 'Bongo Cat', 'a cat plays whatever you type', 'make'],
  ['https://paveldogreat.github.io/WebGL-Fluid-Simulation/', 'Fluid Simulation', 'drag through colourful smoke', 'make'],
  ['http://www.jacksonpollock.org/', 'Jackson Pollock', 'splatter paint with your mouse', 'make'],
  ['https://www.mondrianandme.com/', 'Mondrian and Me', 'make a Mondrian', 'make'],
  ['https://www.puzzlescript.net/', 'PuzzleScript', 'write a puzzle game in an afternoon', 'make'],
  ['https://www.gridzzly.com/', 'Gridzzly', 'print your own grid paper', 'make'],
  ['https://experiments.withgoogle.com/', 'Experiments with Google', 'a few thousand more of these', 'make'],
].map(([url, name, desc, vibe]) => ({ url, name, desc, vibe }));
